### ISSUE TITLE
Help ?

### ISSUE THREAD

**Issue by KeviSoul** [KaiKikuchi/QuickShop#134] opened 2017-06-16 11:58 UTC
the animation of the item won't show on the chest (not even the item ) , i just cant manage to give permission to the default players to create they own shops. 
thank you !

**Comment by KaiKikuchi** [comment] 2017-06-16 16:36
Potential duplicate of #133 

Permissions are listed here: https://www.spigotmc.org/resources/quickshop.18676/

**Closed as completed by KaiKikuchi** 2017-06-16 16:36 UTC

**Comment by KeviSoul** [comment] 2017-06-16 17:29
ty solved.
