### ISSUE TITLE
InventoryCloseEvent exception

### ISSUE THREAD

**Issue by mjra007** [KaiKikuchi/QuickShop#145] opened 2017-07-16 09:25 UTC
I am running a thermos server and basically the plugin is spamming the server with this error.  
Is it thermos that doesnt have the getLocation() method?

> ERROR Could not pass event InventoryCloseEvent to QuickShop v0.9.33
16.07 11:22:33 [Server] INFO org.bukkit.event.EventException
16.07 11:22:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
16.07 11:22:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
16.07 11:22:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
16.07 11:22:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
16.07 11:22:33 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:910) [CraftEventFactory.class:1.7.10-1614.58]
16.07 11:22:33 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147356_a(NetHandlerPlayServer.java:1693) [nh.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(C0DPacketCloseWindow.java:27) [iy.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.network.play.client.C0DPacketCloseWindow.func_148833_a(C0DPacketCloseWindow.java:42) [iy.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
16.07 11:22:33 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
16.07 11:22:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

> 16.07 11:22:33 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getLocation()Lorg/bukkit/Location;
16.07 11:22:33 [Server] INFO at org.maxgamer.quickshop.Listeners.PlayerListener.onInventoryClose(PlayerListener.java:212) ~[?:?]
16.07 11:22:33 [Server] INFO at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source) ~[?:?]
16.07 11:22:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
16.07 11:22:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
16.07 11:22:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
16.07 11:22:33 [Server] INFO ... 14 more

**Comment by KaiKikuchi** [comment] 2017-07-16 09:47
You are not using the latest version. Duplicate of #142.

**Closed as completed by KaiKikuchi** 2017-07-16 09:47 UTC
